# docker-compose.yml

version: '3'
services:
  inventory_service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
