version: '3.8'
services:
  customers_service:
    build: ./customers_service
    ports:
      - "5000:5000"
    volumes:
      - ./customers_service:/app
    environment:
      - FLASK_ENV=development
